name: Release

on:
  release:
    types: [released]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Post release message
      run: |
        jq -f .github/workflows/release_template.jq '${{ github.event_path }}' | curl -H "Content-Type: application/json" -X POST --data-binary @- $DISCORD_WEBHOOK
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

    - name: Deploy to Heroku
      run: |
        heroku login
        heroku git:remote --app=exlibris-production --remote=production
        git push production $GITHUB_REF:refs/heads/main
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
